### ISSUE TITLE
Provide example provider.json

### ISSUE THREAD

**Issue by fostermi** [zmartzone/ngx_openidc_module#10]
I'm trying to configure this module but the example in the README is a little sparse. In particular, what is supposed to be in the provider.json file? I'm using Keycloak and it has an installation json file, but it doesn't look anything like the json file mentioned in https://github.com/zmartzone/ngx_openidc_module/issues/1. Additionally, where are claims set? the line `OpenIDCClaim sub $pfc_claim_sub;` looks like its substituting a variable but no where is is shown what the claim definition should look like. I'm looking for documentation similar to https://github.com/zmartzone/mod_auth_openidc/wiki/Authorization.

**Comment by zandbelt** [comment]
The provider.json file contains the discovery metadata from e.g. https://keycloak.example.net/auth/realms/Testrealm/.well-known/openid-configuration (typically configured as a URL rather than a file).

`OpenIDCClaim sub $pfc_claim_sub;` is pulling the claim "sub" from the id_token or userinfo data and sets it in the `$pfc_claim_sub` variable for later usage, e.g. setting it in a header on a proxied request like `proxy_set_header OAUTH2_CLAIM_sub $pfc_claim_sub;`

**Comment by fostermi** [comment]
Ok thanks. You can close this.
